<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>期约</title>
    </head>
    <body>
        <script>
            // let p = new Promise(() => {});
            // setTimeout(console.log, 0, p);

            // let p1 = new Promise((resolve, reject) => resolve());
            // setTimeout(console.log, 0, p1);

            // let p2 = new Promise((resolve, reject) => reject());
            // setTimeout(console.log, 0, p2);

            // //executor
            // //promise initialized
            // new Promise(() => setTimeout(console.log, 0, 'executor'));
            // setTimeout(console.log, 0, 'promise initialized');

            // //添加 setTimeout 可以推迟切换状态
            // //在console.log 打印期约实例的时候，还不会执行超时回调（即resolve())
            // let p3 = new Promise((resolve, reject) => setTimeout(resolve, 1000));
            // setTimeout(console.log, 0, p3);

            // let p = new Promise((resolve, reject) => {
            //     setTimeout(reject, 10000);  //10秒后调用reject()
            //     // 执行函数的逻辑
            // });

            // // setTimeout(console.log, 0, p);  // Promise <pending>
            // console.log(p);
            // setTimeout(console.log, 11000, p);  // 11秒后再检查状态

            // Promise <resolved>:undefined
            // Promise <resolved>:3
            // Promise <resolved>:4
            // setTimeout(console.log, 0, Promise.resolve());
            // setTimeout(console.log, 0, Promise.resolve(3));
            // setTimeout(console.log, 0, Promise.resolve(4, 5, 6));   //多余的参数会忽略

            // let p = Promise.reject(3);
            // setTimeout(console.log, 0, p);
            // // p.then(null, (e) => setTimeout(console.log, 0, e));

            // let p1 = new Promise((resolve, reject) => resolve(3));
            // setTimeout(console.log, 0, p1);

            // let p2 = new Promise((resolve, reject) => reject("reject reason"));
            // setTimeout(console.log, 0, p2);

            // setTimeout(console.log, 0, Promise.reject(Promise.resolve()));
            // setTimeout(console.log, 0, Promise.resolve(Promise.reject()));

            // 非重入期约方法
            // let synchronousResmolve;

            // 创建一个期约并将解决函数保存在一个局部变量中
            // let p = new Promise((resolve) => {
            //     synchronousResolve = function() {
            //         console.log('1: invoking resolve()');
            //         resolve();
            //         console.log('2: resolve() returns');
            //     };
            // });

            // p.then(() => console.log('4: then() handler executes'));

            // synchronousResolve();
            // console.log('3: synchronousResolve() returns');

            // 实际的输出：
            // 1: invoking resolve()
            // 2: resolve() returns
            // 3: synchronousResolve() returns
            // 4: then() handler executes

            // 如果给期约添加了多个处理程序，当期约状态变化时，
            // 相关处理程序会按照添加它们的顺序依次执行
            // let p1 = Promise.resolve();
            // let p2 = Promise.reject();

            // p1.then(() => setTimeout(console.log, 0, 1));
            // p1.then(() => setTimeout(console.log, 0, 2));
            // p2.then(null, () => setTimeout(console.log, 0, 3));
            // p2.then(null, () => setTimeout(console.log, 0, 4));
            // p2.catch(() => setTimeout(console.log, 0, 5));
            // p2.catch(() => setTimeout(console.log, 0, 6));
            // p1.finally(() => setTimeout(console.log, 0, 7));
            // p1.finally(() => console.log(8));
            // console.log('synchronous');

            // 期约拒绝理由推荐使用错误对象，以便浏览器捕获错误对象中的栈追踪信息
            // let p1 = new Promise((resolve, reject) => reject(Error('foo')));
            // let p2 = new Promise((resolve, reject) => {throw Error('foo')});
            // let p3 = Promise.resolve().then(() => {throw Error('foo')});
            // let p4 = Promise.reject(Error('foo'));

            // setTimeout(console.log, 0, p1);
            // setTimeout(console.log, 0, p2);
            // setTimeout(console.log, 0, p3);
            // setTimeout(console.log, 0, p4);

            // 通过setTimeout执行的函数需要在消息队列排队，等待执行，即使等待时间为0 ！！！
            // 实际的输出：
            // bar1
            // bar
            // setTimeout(console.log, 0, 'bar');  
            // console.log('bar1');

            // throw Error('foo');
            // console.log('bar');  //这一行不会执行

            // 在期约中抛出错误时，因为错误实际上是从消息队列中异步抛出的，
            // 所以并不会阻止运行时继续执行同步指令
            // Promise.reject(Error('foo'));
            // console.log('bar');

            // Promise.all()
            // let p = Promise.all([Promise.reject(3),
            //     new Promise((resolve, reject) => {
            //     console.log(4);
            //     resolve(4);
            // }), new Promise((resolve, reject) => {
            //     console.log(5);
            //     reject(5);
            // })]);
            // p.catch((reason) => setTimeout(console.log, 0, reason));

            // Promise.race()
            // let p = Promise.race([Promise.reject(3),
            //     new Promise((resolve, reject) => {
            //     console.log(4);
            //     resolve(4);
            // }), new Promise((resolve, reject) => {
            //     console.log(5);
            //     reject(5);
            // })]);
            // p.catch((reason) => setTimeout(console.log, 0, reason));

            // Promise.resolve 返回值是 后续处理程序的第一个参数
            // function addTwo(x) {return x+2};
            // function addThree(x) {return x+3};
            // function addFive(x) {return x+5};

            // function addTen(x) {
            //     return Promise.resolve(x)
            //     .then(addTwo)    // 返回值作为处理程序的第一个参数
            //     .then(addThree)
            //     .then(addFive);
            // }
            // addTen(8).then(console.log);
        </script>
    </body>
</html>